#server:
#  port: 80
#
##TRACE（追踪）：最低的日志级别，用于最详细的日志记录，一般用于调试和跟踪代码执行路径。
##
##DEBUG（调试）：用于调试应用程序时打印详细的信息，例如变量的值、方法的执行路径等。
##
##INFO（信息）：用于打印一般的信息日志，例如应用程序启动信息、请求处理成功的提示等。
##
##WARN（警告）：用于表示潜在的问题或不合理的操作，但不会影响应用程序的正常运行。
##
##ERROR（错误）：用于记录错误事件，例如未捕获的异常、无法连接到数据库等严重错误。
##
##FATAL（致命）：最高的日志级别，用于记录非常严重的错误事件，通常会导致应用程序无法继续运行。
#
#logging:
#  level:
#    root: info
#
##自定义的属性
#likes:
#  - music
#  - game
#  - PE
#
#
#lesson: SpringBoot
#
#
#enterprise:
#  name: itcast
#  age: 16
#  tel: 4006184000
#  subject:
#    - Java
#    - 前端
#    - 大数据